version: '3.8'

services:
  flask-etl-dashboard:
    image: mahsanazarii/flask-etl-dashboard:latest
    container_name: flask-etl-dashboard
    ports:
      - "5001:5000"
    environment:
      - FLASK_APP=app.dashboard
      - FLASK_ENV=development
      - DOCKER_ENV=true
      - SECRET_KEY=your_super_secret_key
    networks:
      - etl_dashboard_network
    volumes:
      - ./uploads:/app/uploads
      - ./etl_info:/app/etl_info

networks:
  etl_dashboard_network:
    driver: bridge
