name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3


      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: mahsanazarii/flask-etl-dashboard:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3


      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose


      - name: Deploy with Docker Compose
        run: |
          docker-compose down
          docker-compose pull
          docker-compose up -d
